# Setup
title:               CSCI 362
tagline:             'Chloe Harris - Fall 2020'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://chh-2.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Chloe Harris
  url:               https://chh-2.github.io
  email:             harriscn@g.cofc.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
